import 'package:flutter/material.dart';
import 'dart:ui';

class Constructor {
  String name;
  String rank;
  String points;
  Color? color;
  String logoUrl;
  String carUrl;
  String constructorChampionships;
  String wins;
  String polePositions;
  String fastestLaps;
  String driver1;
  String driver1Url;
  String driver2;
  String driver2Url;
  String driver1_fname;
  String driver1_lname;
  String driver2_fname;
  String driver2_lname;
  String teamChief;
  String chasis;
  String powerUnit;

  Constructor ({
    required this.name,
    required this.rank,
    required this.points,
    required this.color,
    required this.logoUrl,
    required this.carUrl,
    required this.constructorChampionships,
    required this.wins,
    required this.polePositions,
    required this.fastestLaps,
    required this.driver1,
    required this.driver1Url,
    required this.driver2,
    required this.driver2Url,
    required this.driver1_fname,
    required this.driver1_lname,
    required this.driver2_fname,
    required this.driver2_lname,
    required this.teamChief,
    required this.chasis,
    required this.powerUnit,

  });
}

List<Constructor> constructors = [
  Constructor(
    name: 'Red Bull Racing',
    rank: '1',
    points: '286',
    color: Colors.blue[800],
    logoUrl: 'assets/images/RedBull_img.png',
    carUrl: 'assets/images/RedBull_car.png',
    constructorChampionships: '4',
    wins: '70',
    polePositions: '67',
    fastestLaps: '72',
    driver1: 'Max Verstappen',
    driver2: 'Sergio Perez',
    driver1Url: 'assets/images/MaxVerstappen_img.png',
    driver2Url: 'assets/images/SergioPerez_img.png',
    driver1_fname: 'Max ',
    driver1_lname: 'Verstappen',
    driver2_fname: 'Sergio ',
    driver2_lname: 'Perez',
    teamChief: 'Christian Horner',
    chasis: 'RB16B',
    powerUnit: 'Honda'
  ),
  Constructor(
    name: 'Mercedes',
    rank: '2',
    points: '242',
    color: Colors.tealAccent,
    logoUrl: 'assets/images/Mercedes_img.png',
    carUrl: 'assets/images/Mercedes_car.png',
    constructorChampionships: '7',
    wins: '109',
    polePositions: '121',
    fastestLaps: '80',
    driver1: 'Lewis Hamilton',
    driver2: 'Valtteri Bottas',
    driver1Url: 'assets/images/LewisHamilton_img.png',
    driver2Url: 'assets/images/ValtteriBottas_img.png',
    driver1_fname: 'Lewis ',
    driver1_lname: 'Hamilton',
    driver2_fname: 'Valtteri ',
    driver2_lname: 'Bottas',
    teamChief: 'Toto Wolf',
    chasis: 'W12',
    powerUnit: 'Mercedes'
  ),
  Constructor(
    name: 'McLaren',
    rank: '3',
    points: '141',
    color: Colors.yellow[700],
    logoUrl: 'assets/images/Mclaren_img.png',
    carUrl: 'assets/images/McLaren_car.png',
    constructorChampionships: '8',
    wins: '182',
    polePositions: '155',
    fastestLaps: '158',
    driver1: 'Lando Norris',
    driver2: 'Daniel Ricciardo',
    driver1Url: 'assets/images/LandoNorris_img',
    driver2Url: 'assets/images/DanielRicciardo_img.png',
    driver1_fname: 'Lando ',
    driver1_lname: 'Norris',
    driver2_fname: 'Daniel ',
    driver2_lname: 'Ricciardo',
    teamChief: 'Andreas Seidl',
    chasis: 'MCL35M',
    powerUnit: 'Mercedes'
  ),
  Constructor(
    name: 'Ferrari',
    rank: '4',
    points: '122',
    color: Colors.red[600],
    logoUrl: 'assets/images/Ferrari_img.png',
    carUrl: 'assets/images/Ferrari_car.png',
    constructorChampionships: '16',
    wins: '239',
    polePositions: '223',
    fastestLaps: '253',
    driver1: 'Charles Leclerc',
    driver2: 'Carlos Sainz',
    driver1Url: 'assets/images/CharlesLeclerc_img.png',
    driver2Url: 'assets/images/CarlosSainz_img',
    driver1_fname: 'Charles ',
    driver1_lname: 'Leclerc',
    driver2_fname: 'Carlos ',
    driver2_lname: 'Sainz',
    teamChief: 'Mattia Binotto',
    chasis: 'SF21',
    powerUnit: 'Ferrari'
  ),
  Constructor(
    name: 'AlphaTauri',
    rank: '5',
    points: '48',
    color: Colors.grey[900],
    logoUrl: 'assets/images/AlphaTauri_img.png',
    carUrl: 'assets/images/AlphaTauri_car.png',
    constructorChampionships: '0',
    wins: '12',
    polePositions: '1',
    fastestLaps: '1',
    driver1: 'Pierre Gasly',
    driver2: 'Yuki Tsunoda',
    driver1Url: 'assets/images/PierreGasly_img.png',
    driver2Url: 'assets/images/YukiTsunoda_img.png',
    driver1_fname: 'Pierre ',
    driver1_lname: 'Gasly',
    driver2_fname: 'Yuki ',
    driver2_lname: 'Tsunoda',
    teamChief: 'Franz Tost',
    chasis: 'AT02',
    powerUnit: 'Honda'
  ),
  Constructor(
    name: 'Aston Martin',
    rank: '6',
    points: '44',
    color: Colors.green[900],
    logoUrl: 'assets/images/AstonMartingRacing_img.png',
    carUrl: 'assets/images/AstonMartin_car.png',
    constructorChampionships: '0',
    wins: '1',
    polePositions: '1',
    fastestLaps: '0',
    driver1: 'Sebastian Vettel',
    driver2: 'Lance Stroll',
    driver1Url: 'assets/images/SebastianVettel_img.png',
    driver2Url: 'assets/images/LanceStroll_img',
    driver1_fname: 'Sebastian ',
    driver1_lname: 'Vettel',
    driver2_fname: 'Lance ',
    driver2_lname: 'Stroll',
    teamChief: 'Otmar Szafnauer',
    chasis: 'AMR21',
    powerUnit: 'Mercedes'
  ),
  Constructor(
    name: 'Alpine',
    rank: '7',
    points: '32',
    color: Colors.lightBlue,
    logoUrl: 'assets/images/Alpine_img.png',
    carUrl: 'assets/images/Alpine_car.png',
    constructorChampionships: '2',
    wins: '20',
    polePositions: '20',
    fastestLaps: '15',
    driver1: 'Fernando Alonso',
    driver2: 'Esteban Ocon',
    driver1Url: 'assets/images/FernandoAlonso_img.png',
    driver2Url: 'assets/images/EstebanOcon_img.png',
    driver1_fname: 'Fernando ',
    driver1_lname: 'Alonso',
    driver2_fname: 'Esteban ',
    driver2_lname: 'Ocon',
    teamChief: 'Davide Brivio',
    chasis: 'A521',
    powerUnit: 'Renault'
  ),
  Constructor(
    name: 'Alfa Romeo Racing',
    rank: '8',
    points: '2',
    color: Colors.red[900],
    logoUrl: 'assets/images/AlfaRomeo_img.png',
    carUrl: 'assets/images/AlfaRomeoRacing_car.png',
    constructorChampionships: '0',
    wins: '1',
    polePositions: '1',
    fastestLaps: '5',
    driver1: 'Kimi Räikkönen',
    driver2: 'Antonio Giovinazzi',
    driver1Url: 'assets/images/KimiRaikonen_img.png',
    driver2Url: 'assets/images/AntonioGiovinazzi_img.png',
    driver1_fname: 'Kimi ',
    driver1_lname: 'Räikkönen',
    driver2_fname: 'Antonio ',
    driver2_lname: 'Giovinazzi',
    teamChief: 'Frédéric Vasseur',
    chasis: 'C41',
    powerUnit: 'Ferrari'
  ),
  Constructor(
    name: 'Williams',
    rank: '9',
    points: '0',
    color: Colors.blue[700],
    logoUrl: 'assets/images/Williams_img.png',
    carUrl: 'assets/images/Williams_car.png',
    constructorChampionships: '9',
    wins: '114',
    polePositions: '129',
    fastestLaps: '122',
    driver1: 'George Russel',
    driver2: 'Nicholas Latifi',
    driver1Url: 'assets/images/GeorgeRussel_img.png',
    driver2Url: 'assets/images/NicholasLatiffi_img.png',
    driver1_fname: 'George ',
    driver1_lname: 'Russel',
    driver2_fname: 'Nicholas ',
    driver2_lname: 'Latifi',
    teamChief: 'Jost Capito',
    chasis: 'FW43B',
    powerUnit: 'Mercedes'
  ),
  Constructor(
    name: 'Haas F1 Team',
    rank: '10',
    points: '0',
    color: Colors.grey[400],
    logoUrl: 'assets/images/Haas_img.png',
    carUrl: 'assets/images/Haas_car.png',
    constructorChampionships: '0',
    wins: '0',
    polePositions: '0',
    fastestLaps: '2',
    driver1: 'Mick Schumacher',
    driver2: 'Nikita Mazepin',
    driver1Url: 'assets/images/MickSchumacher_img.png',
    driver2Url: 'assets/images/NikitaMazepin_img.png',
    driver1_fname: 'Mick ',
    driver1_lname: 'Schumacher',
    driver2_fname: 'Nikita ',
    driver2_lname: 'Mazepin',
    teamChief: 'Guenther Steiner',
    chasis: 'VF-21',
    powerUnit: 'Ferrari'
  ),
];