class PictureCarousel {
  String maxVerstappen;
  String lewisHamilton;
  String sergioPerez;
  String landoNorris;
  String valterriBottas;
  String charlesLeclerc;
  String carlosSainz;
  String danielRicciardo;
  String pierreGasly;
  String sebastianVettel;
  String fernandoAlonso;
  String lanceStroll;
  String estebanOcon;
  String yukiTsunoda;
  String kimiRaikkonen;
  String antonioGiovinazzi;
  String georgeRussel;
  String mickSchumacher;
  String nikitaMazepin;
  String nicholasLatifi;

  PictureCarousel({
    required this.maxVerstappen,
    required this.lewisHamilton,
    required this.sergioPerez,
    required this.landoNorris,
    required this.valterriBottas,
    required this.charlesLeclerc,
    required this.carlosSainz,
    required this.danielRicciardo,
    required this.pierreGasly,
    required this.sebastianVettel,
    required this.fernandoAlonso,
    required this.lanceStroll,
    required this.estebanOcon,
    required this.yukiTsunoda,
    required this.kimiRaikkonen,
    required this.antonioGiovinazzi,
    required this.georgeRussel,
    required this.mickSchumacher,
    required this.nikitaMazepin,
    required this.nicholasLatifi,
  });
}

List<PictureCarousel> pictureCarousels = [
  PictureCarousel(
    maxVerstappen: 'assets/images/MaxVerstappen1.jpg',
    lewisHamilton: 'assets/images/LewisHamilton1.jpg',
    sergioPerez: 'assets/images/SergioPerez1.jpg',
    landoNorris: 'assets/images/LandoNorris1.jpg',
    valterriBottas: 'assets/images/ValtteriBottas1.jpg',
    charlesLeclerc: 'assets/images/CharlesLeclerc1.jpg',
    carlosSainz: 'assets/images/CarlosSainz1.jpg',
    danielRicciardo: 'assets/images/DanielRicciardo1.jpg',
    pierreGasly: 'assets/images/PierreGasly1.jpg',
    sebastianVettel: 'assets/images/SebastianVettel1.jpg',
    fernandoAlonso: 'assets/images/FernandoAlonso1.jpg',
    lanceStroll: 'assets/images/LanceStroll1.jpg',
    estebanOcon: 'assets/images/EstebanOcon1.jpg',
    yukiTsunoda: 'assets/images/YukiTsunoda1.jpg',
    kimiRaikkonen: 'assets/images/KimiRaikkonen1.jpg',
    antonioGiovinazzi: 'assets/images/AntonioGiovinazzi1.jpg',
    georgeRussel: 'assets/images/GeorgeRussel1.jpg',
    mickSchumacher: 'assets/images/MickSchumacher1.jpg',
    nikitaMazepin: 'assets/images/NikitaMazepin1.jpg',
    nicholasLatifi: 'assets/images/NicholasLatiffi1.jpg',
  ),
  PictureCarousel(
    maxVerstappen: 'assets/images/MaxVerstappen2.jpg',
    lewisHamilton: 'assets/images/LewisHamilton2.jpg',
    sergioPerez: 'assets/images/SergioPerez2.jpg',
    landoNorris: 'assets/images/LandoNorris2.jpg',
    valterriBottas: 'assets/images/ValtteriBottas2.jpg',
    charlesLeclerc: 'assets/images/CharlesLeclerc2.jpg',
    carlosSainz: 'assets/images/CarlosSainz2.jpg',
    danielRicciardo: 'assets/images/DanielRicciardo2.jpg',
    pierreGasly: 'assets/images/PierreGasly2.jpg',
    sebastianVettel: 'assets/images/SebastianVettel2.jpg',
    fernandoAlonso: 'assets/images/FernandoAlonso2.jpg',
    lanceStroll: 'assets/images/LanceStroll2.jpg',
    estebanOcon: 'assets/images/EstebanOcon2.jpg',
    yukiTsunoda: 'assets/images/YukiTsunoda2.jpg',
    kimiRaikkonen: 'assets/images/KimiRaikkonen2.jpg',
    antonioGiovinazzi: 'assets/images/AntonioGiovinazzi2.jpg',
    georgeRussel: 'assets/images/GeorgeRussel2.jpg',
    mickSchumacher: 'assets/images/MickSchumacher2.jpg',
    nikitaMazepin: 'assets/images/NikitaMazepin2.jpg',
    nicholasLatifi: 'assets/images/NicholasLatiffi2.jpg',
  ),
  PictureCarousel(
    maxVerstappen: 'assets/images/MaxVerstappen3.jpg',
    lewisHamilton: 'assets/images/LewisHamilton3.jpg',
    sergioPerez: 'assets/images/SergioPerez3.jpg',
    landoNorris: 'assets/images/LandoNorris3.jpg',
    valterriBottas: 'assets/images/ValtteriBottas3.jpg',
    charlesLeclerc: 'assets/images/CharlesLeclerc3.jpg',
    carlosSainz: 'assets/images/CarlosSainz3.jpg',
    danielRicciardo: 'assets/images/DanielRicciardo3.jpg',
    pierreGasly: 'assets/images/PierreGasly3.jpg',
    sebastianVettel: 'assets/images/SebastianVettel3.jpg',
    fernandoAlonso: 'assets/images/FernandoAlonso3.jpg',
    lanceStroll: 'assets/images/LanceStroll3.jpg',
    estebanOcon: 'assets/images/EstebanOcon3.jpg',
    yukiTsunoda: 'assets/images/YukiTsunoda3.jpg',
    kimiRaikkonen: 'assets/images/KimiRaikkonen3.jpg',
    antonioGiovinazzi: 'assets/images/AntonioGiovinazzi3.jpg',
    georgeRussel: 'assets/images/GeorgeRussel3.jpg',
    mickSchumacher: 'assets/images/MickSchumacher3.jpg',
    nikitaMazepin: 'assets/images/NikitaMazepin3.jpg',
    nicholasLatifi: 'assets/images/NicholasLatiffi3.jpg',
  ),
  PictureCarousel(
    maxVerstappen: 'assets/images/MaxVerstappen4.jpg',
    lewisHamilton: 'assets/images/LewisHamilton4.jpg',
    sergioPerez: 'assets/images/SergioPerez4.jpg',
    landoNorris: 'assets/images/LandoNorris4.jpg',
    valterriBottas: 'assets/images/ValtteriBottas4.jpg',
    charlesLeclerc: 'assets/images/CharlesLeclerc4.jpg',
    carlosSainz: 'assets/images/CarlosSainz4.jpg',
    danielRicciardo: 'assets/images/DanielRicciardo4.jpg',
    pierreGasly: 'assets/images/PierreGasly4.jpg',
    sebastianVettel: 'assets/images/SebastianVettel4.jpg',
    fernandoAlonso: 'assets/images/FernandoAlonso4.jpg',
    lanceStroll: 'assets/images/LanceStroll4.jpg',
    estebanOcon: 'assets/images/EstebanOcon4.jpg',
    yukiTsunoda: 'assets/images/YukiTsunoda4.jpg',
    kimiRaikkonen: 'assets/images/KimiRaikkonen4.jpg',
    antonioGiovinazzi: 'assets/images/AntonioGiovinazzi4.jpg',
    georgeRussel: 'assets/images/GeorgeRussel4.jpg',
    mickSchumacher: 'assets/images/MickSchumacher4.jpg',
    nikitaMazepin: 'assets/images/NikitaMazepin4.jpg',
    nicholasLatifi: 'assets/images/NicholasLatiffi4.jpg',
  ),
  PictureCarousel(
    maxVerstappen: 'assets/images/MaxVerstappen5.jpg',
    lewisHamilton: 'assets/images/LewisHamilton5.jpg',
    sergioPerez: 'assets/images/SergioPerez5.jpg',
    landoNorris: 'assets/images/LandoNorris5.jpg',
    valterriBottas: 'assets/images/ValtteriBottas5.jpg',
    charlesLeclerc: 'assets/images/CharlesLeclerc5.jpg',
    carlosSainz: 'assets/images/CarlosSainz5.jpg',
    danielRicciardo: 'assets/images/DanielRicciardo5.jpg',
    pierreGasly: 'assets/images/PierreGasly5.jpg',
    sebastianVettel: 'assets/images/SebastianVettel5.jpg',
    fernandoAlonso: 'assets/images/FernandoAlonso5.jpg',
    lanceStroll: 'assets/images/LanceStroll5.jpg',
    estebanOcon: 'assets/images/EstebanOcon5.jpg',
    yukiTsunoda: 'assets/images/YukiTsunoda5.jpg',
    kimiRaikkonen: 'assets/images/KimiRaikkonen5.jpg',
    antonioGiovinazzi: 'assets/images/AntonioGiovinazzi5.jpg',
    georgeRussel: 'assets/images/GeorgeRussel5.jpg',
    mickSchumacher: 'assets/images/MickSchumacher5.jpg',
    nikitaMazepin: 'assets/images/NikitaMazepin5.jpg',
    nicholasLatifi: 'assets/images/NicholasLatiffi5.jpg',
  ),
  PictureCarousel(
    maxVerstappen: 'assets/images/MaxVerstappen6.jpg',
    lewisHamilton: 'assets/images/LewisHamilton6.jpg',
    sergioPerez: 'assets/images/SergioPerez6.jpg',
    landoNorris: 'assets/images/LandoNorris6.jpg',
    valterriBottas: 'assets/images/ValtteriBottas6.jpg',
    charlesLeclerc: 'assets/images/CharlesLeclerc6.jpg',
    carlosSainz: 'assets/images/CarlosSainz6.jpg',
    danielRicciardo: 'assets/images/DanielRicciardo6.jpg',
    pierreGasly: 'assets/images/PierreGasly6.jpg',
    sebastianVettel: 'assets/images/SebastianVettel6.jpg',
    fernandoAlonso: 'assets/images/FernandoAlonso6.jpg',
    lanceStroll: 'assets/images/LanceStroll6.jpg',
    estebanOcon: 'assets/images/EstebanOcon6.jpg',
    yukiTsunoda: 'assets/images/YukiTsunoda6.jpg',
    kimiRaikkonen: 'assets/images/KimiRaikkonen6.jpg',
    antonioGiovinazzi: 'assets/images/AntonioGiovinazzi6.jpg',
    georgeRussel: 'assets/images/GeorgeRussel6.jpg',
    mickSchumacher: 'assets/images/MickSchumacher6.jpg',
    nikitaMazepin: 'assets/images/NikitaMazepin6.jpg',
    nicholasLatifi: 'assets/images/NicholasLatiffi6.jpg',
  ),
];