class PictureCarousel {
  String image1url;
  String image2url;
  String image3url;
  String image4url;
  String image5url;
  String image6url;

  PictureCarousel({
    required this.image1url,
    required this.image2url,
    required this.image3url,
    required this.image4url,
    required this.image5url,
    required this.image6url,
  });
}

List<PictureCarousel> pictureCarousels = [
   PictureCarousel(
     image1url: 'assets/images/MaxVerstappen1.jpg',
     image2url: 'assets/images/MaxVerstappen2.jpg',
     image3url: 'assets/images/MaxVerstappen3.jpg',
     image4url: 'assets/images/MaxVerstappen4.jpg',
     image5url: 'assets/images/MaxVerstappen5.jpg',
     image6url: 'assets/images/MaxVerstappen6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/LewisHamilton1.jpg',
     image2url: 'assets/images/LewisHamilton2.jpg',
     image3url: 'assets/images/LewisHamilton3.jpg',
     image4url: 'assets/images/LewisHamilton4.jpg',
     image5url: 'assets/images/LewisHamilton5.jpg',
     image6url: 'assets/images/LewisHamilton6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/SergioPerez1.jpg',
     image2url: 'assets/images/SergioPerez2.jpg',
     image3url: 'assets/images/SergioPerez3.jpg',
     image4url: 'assets/images/SergioPerez4.jpg',
     image5url: 'assets/images/SergioPerez5.jpg',
     image6url: 'assets/images/SergioPerez6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/LandoNorris1.jpg',
     image2url: 'assets/images/LandoNorris2.jpg',
     image3url: 'assets/images/LandoNorris3.jpg',
     image4url: 'assets/images/LandoNorris4.jpg',
     image5url: 'assets/images/LandoNorris5.jpg',
     image6url: 'assets/images/LandoNorris6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/ValtteriBottas1.jpg',
     image2url: 'assets/images/ValtteriBottas2.jpg',
     image3url: 'assets/images/ValtteriBottas3.jpg',
     image4url: 'assets/images/ValtteriBottas4.jpg',
     image5url: 'assets/images/ValtteriBottas5.jpg',
     image6url: 'assets/images/ValtteriBottas6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/CharlesLeclerc1.jpg',
     image2url: 'assets/images/CharlesLeclerc2.jpg',
     image3url: 'assets/images/CharlesLeclerc3.jpg',
     image4url: 'assets/images/CharlesLeclerc4.jpg',
     image5url: 'assets/images/CharlesLeclerc5.jpg',
     image6url: 'assets/images/CharlesLeclerc6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/CarlosSainz1.jpg',
     image2url: 'assets/images/CarlosSainz2.jpg',
     image3url: 'assets/images/CarlosSainz3.jpg',
     image4url: 'assets/images/CarlosSainz4.jpg',
     image5url: 'assets/images/CarlosSainz5.jpg',
     image6url: 'assets/images/CarlosSainz6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/DanielRicciardo1.jpg',
     image2url: 'assets/images/DanielRicciardo2.jpg',
     image3url: 'assets/images/DanielRicciardo3.jpg',
     image4url: 'assets/images/DanielRicciardo4.jpg',
     image5url: 'assets/images/DanielRicciardo5.jpg',
     image6url: 'assets/images/DanielRicciardo6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/PierreGasly1.jpg',
     image2url: 'assets/images/PierreGasly2.jpg',
     image3url: 'assets/images/PierreGasly3.jpg',
     image4url: 'assets/images/PierreGasly4.jpg',
     image5url: 'assets/images/PierreGasly5.jpg',
     image6url: 'assets/images/PierreGasly6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/SebastianVettel1.jpg',
     image2url: 'assets/images/SebastianVettel2.jpg',
     image3url: 'assets/images/SebastianVettel3.jpg',
     image4url: 'assets/images/SebastianVettel4.jpg',
     image5url: 'assets/images/SebastianVettel5.jpg',
     image6url: 'assets/images/SebastianVettel6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/FernandoAlonso1.jpg',
     image2url: 'assets/images/FernandoAlonso2.jpg',
     image3url: 'assets/images/FernandoAlonso3.jpg',
     image4url: 'assets/images/FernandoAlonso4.jpg',
     image5url: 'assets/images/FernandoAlonso5.jpg',
     image6url: 'assets/images/FernandoAlonso6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/LanceStroll1.jpg',
     image2url: 'assets/images/LanceStroll2.jpg',
     image3url: 'assets/images/LanceStroll3.jpg',
     image4url: 'assets/images/LanceStroll4.jpg',
     image5url: 'assets/images/LanceStroll5.jpg',
     image6url: 'assets/images/LanceStroll6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/EstebanOcon1.jpg',
     image2url: 'assets/images/EstebanOcon2.jpg',
     image3url: 'assets/images/EstebanOcon3.jpg',
     image4url: 'assets/images/EstebanOcon4.jpg',
     image5url: 'assets/images/EstebanOcon5.jpg',
     image6url: 'assets/images/EstebanOcon6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/YukiTsunoda1.jpg',
     image2url: 'assets/images/YukiTsunoda2.jpg',
     image3url: 'assets/images/YukiTsunoda3.jpg',
     image4url: 'assets/images/YukiTsunoda4.jpg',
     image5url: 'assets/images/YukiTsunoda5.jpg',
     image6url: 'assets/images/YukiTsunoda6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/KimiRaikkonen1.jpg',
     image2url: 'assets/images/KimiRaikkonen2.jpg',
     image3url: 'assets/images/KimiRaikkonen3.jpg',
     image4url: 'assets/images/KimiRaikkonen4.jpg',
     image5url: 'assets/images/KimiRaikkonen5.jpg',
     image6url: 'assets/images/KimiRaikkonen6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/AntonioGiovinazzi1.jpg',
     image2url: 'assets/images/AntonioGiovinazzi2.jpg',
     image3url: 'assets/images/AntonioGiovinazzi3.jpg',
     image4url: 'assets/images/AntonioGiovinazzi4.jpg',
     image5url: 'assets/images/AntonioGiovinazzi5.jpg',
     image6url: 'assets/images/AntonioGiovinazzi6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/GeorgeRussel1.jpg',
     image2url: 'assets/images/GeorgeRussel2.jpg',
     image3url: 'assets/images/GeorgeRussel3.jpg',
     image4url: 'assets/images/GeorgeRussel4.jpg',
     image5url: 'assets/images/GeorgeRussel5.jpg',
     image6url: 'assets/images/GeorgeRussel6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/MickSchumacher1.jpg',
     image2url: 'assets/images/MickSchumacher2.jpg',
     image3url: 'assets/images/MickSchumacher3.jpg',
     image4url: 'assets/images/MickSchumacher4.jpg',
     image5url: 'assets/images/MickSchumacher5.jpg',
     image6url: 'assets/images/MickSchumacher6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/NikitaMazepin1.jpg',
     image2url: 'assets/images/NikitaMazepin2.jpg',
     image3url: 'assets/images/NikitaMazepin3.jpg',
     image4url: 'assets/images/NikitaMazepin4.jpg',
     image5url: 'assets/images/NikitaMazepin5.jpg',
     image6url: 'assets/images/NikitaMazepin6.jpg',
   ),
   PictureCarousel(
     image1url: 'assets/images/NicholasLatiffi1.jpg',
     image2url: 'assets/images/NicholasLatiffi2.jpg',
     image3url: 'assets/images/NicholasLatiffi3.jpg',
     image4url: 'assets/images/NicholasLatiffi4.jpg',
     image5url: 'assets/images/NicholasLatiffi5.jpg',
     image6url: 'assets/images/NicholasLatiffi6.jpg',
   ),
 ];