class Race {
  String round;
  String date;
  String month;
  String backgroundUrl;
  String location;
  String venue;
  String flagUrl;
  String trackUrl;
  String circuitLength;
  String noLaps;
  String firstGp;
  String raceDistance;
  String lapRecordTime;
  String lapRecordHolderYear;

  Race({
    required this.round,
    required this.date,
    required this.month,
    required this.backgroundUrl,
    required this.location,
    required this.venue,
    required this.flagUrl,
    required this.trackUrl,
    required this.circuitLength,
    required this.noLaps,
    required this.firstGp,
    required this.raceDistance,
    required this.lapRecordTime,
    required this.lapRecordHolderYear,
  });
}

List <Race> races = [
  Race(
    round: 'Testing',
    date: '12-14',
    month: 'Mar',
    backgroundUrl: 'assets/images/preseason_bg.jpg',
    location: 'Pre-Season Test',
    venue: 'Bahrain International \nCircuit',
    flagUrl: 'assets/images/preseason_flag.png',
    trackUrl: 'assets/images/preseason_track.png',
    circuitLength: '5.412',
    noLaps: 'N/A',
    firstGp: '2004',
    raceDistance: 'N/A',
    lapRecordTime: '1:31.447',
    lapRecordHolderYear: 'Pedro de la Rosa (2005)'
  ),
  Race(
    round: 'Round 1',
    date: '26-28',
    month: 'Mar',
    backgroundUrl: 'assets/images/bahrain_bg.jpg',
    location: 'Bahrain',
    venue: 'Bahrain International \nCircuit',
    flagUrl: 'assets/images/bahrain_flag.png',
    trackUrl: 'assets/images/bahrain_track.png',
    circuitLength: '5.412',
    noLaps: '57',
    firstGp: '2004',
    raceDistance: '308.238',
    lapRecordTime: '1:31.447',
    lapRecordHolderYear: 'Pedro de la Rosa (2005)'
  ),
  Race(
    round: 'Round 2',
    date: '16-18',
    month: 'Apr',
    backgroundUrl: 'assets/images/italy_bg.jpg',
    location: 'Italy',
    venue: 'Autodromo Enzo e \nDino Ferrari',
    flagUrl: 'assets/images/italy_flag.png',
    trackUrl: 'assets/images/italy_track.png',
    circuitLength: '4.909',
    noLaps: '63',
    firstGp: '1980',
    raceDistance: '309.049',
    lapRecordTime: '1:15.484',
    lapRecordHolderYear: 'Lewis Hamilton (2020)'
  ),
  Race(
    round: 'Round 3',
    date: '30-02',
    month: 'Apr-May',
    backgroundUrl: 'assets/images/portugal_bg.jpg',
    location: 'Portugal',
    venue: 'Autódromo Internacional \ndo Algarve',
    flagUrl: 'assets/images/portugal_flag.png',
    trackUrl: 'assets/images/portugal_track.png',
    circuitLength: '4.653',
    noLaps: '66',
    firstGp: '2020',
    raceDistance: '306.826',
    lapRecordTime: '1:18.750',
    lapRecordHolderYear: 'Lewis Hamilton (2020)'
  ),
  Race(
    round: 'Round 4',
    date: '07-09',
    month: 'May',
    backgroundUrl: 'assets/images/spain_bg.jpg',
    location: 'Spain',
    venue: 'Circuit de \nBarcelona-Catalunya',
    flagUrl: 'assets/images/spain_flag.png',
    trackUrl: 'assets/images/spain_track.png',
    circuitLength: '4.675',
    noLaps: '66',
    firstGp: '1991',
    raceDistance: '308.424',
    lapRecordTime: '1:18.149',
    lapRecordHolderYear: 'Max Verstappen (2021)'
  ),
  Race(
    round: 'Round 5',
    date: '20-23',
    month: 'May',
    backgroundUrl: 'assets/images/monaco_bg.jpg',
    location: 'Monaco',
    venue: 'Circuit de Monaco',
    flagUrl: 'assets/images/monaco_flag.png',
    trackUrl: 'assets/images/monaco_track.png',
    circuitLength: '3.337',
    noLaps: '78',
    firstGp: '1950',
    raceDistance: '260.286',
    lapRecordTime: '1:12.909',
    lapRecordHolderYear: 'Lewis Hamilton (2021)'
  ),
  Race(
    round: 'Round 6',
    date: '04-06',
    month: 'Jun',
    backgroundUrl: 'assets/images/azerbaijan_bg.jpg',
    location: 'Azerbaijan',
    venue: 'Baku City Circuit',
    flagUrl: 'assets/images/azerbaijan_flag.png',
    trackUrl: 'assets/images/azerbaijan_track.png',
    circuitLength: '6.003',
    noLaps: '51',
    firstGp: '2016',
    raceDistance: '306.049',
    lapRecordTime: '1:43.009',
    lapRecordHolderYear: 'Charles Leclerc (2019)'
  ),
  Race(
    round: 'Round 7',
    date: '18-20',
    month: 'Jun',
    backgroundUrl: 'assets/images/france_bg.jpg',
    location: 'France',
    venue: 'Circuit Paul \nRicard',
    flagUrl: 'assets/images/france_flag.png',
    trackUrl: 'assets/images/france_track.png',
    circuitLength: '5.842',
    noLaps: '53',
    firstGp: '1971',
    raceDistance: '309.69',
    lapRecordTime: '1:32.740',
    lapRecordHolderYear: 'Sebastian Vettel (2019)'
  ),
  Race(
    round: 'Round 8',
    date: '25-27',
    month: 'Jun',
    backgroundUrl: 'assets/images/austria_bg.jpg',
    location: 'Austria',
    venue: 'Red Bull Ring',
    flagUrl: 'assets/images/austria_flag.png',
    trackUrl: 'assets/images/austria_track.png',
    circuitLength: '4.318',
    noLaps: '71',
    firstGp: '1970',
    raceDistance: '306.452',
    lapRecordTime: '1:05.619',
    lapRecordHolderYear: 'Carlos Sainz (2020)'
  ),
  Race(
    round: 'Round 9',
    date: '02-04',
    month: 'Jul',
    backgroundUrl: 'assets/images/austria2_bg.jpg',
    location: 'Austria',
    venue: 'Red Bull Ring',
    flagUrl: 'assets/images/austria2_flag.png',
    trackUrl: 'assets/images/austria2_track.png',
    circuitLength: '4.318',
    noLaps: '71',
    firstGp: '1970',
    raceDistance: '306.452',
    lapRecordTime: '1:05.619',
    lapRecordHolderYear: 'Carlos Sainz (2020)',
  ),
  Race(
    round: 'Round 10',
    date: '16-18',
    month: 'Jul',
    backgroundUrl: 'assets/images/greatBritain_bg.jpg',
    location: 'Great Britain',
    venue: 'Silverstone Circuit',
    flagUrl: 'assets/images/greatBritain_flag.png',
    trackUrl: 'assets/images/greatBritain_track.png',
    circuitLength: '5.891',
    noLaps: '52',
    firstGp: '1950',
    raceDistance: '306.198',
    lapRecordTime: '1:27.097',
    lapRecordHolderYear: 'Max Verstappen (2020)',
  ),
  Race(
    round: 'Round 11',
    date: '30-01',
    month: 'Jul-Aug',
    backgroundUrl: 'assets/images/hungary_bg.jpg',
    location: 'Hungary',
    venue: 'Hungaroring',
    flagUrl: 'assets/images/hungary_flag.png',
    trackUrl: 'assets/images/hungary_track.png',
    circuitLength: '4.381',
    noLaps: '70',
    firstGp: '1950',
    raceDistance: '306.63',
    lapRecordTime: '1:16.627',
    lapRecordHolderYear: 'Lewis Hamilton (2020)',
  ),
  Race(
    round: 'Round 12',
    date: '27-29',
    month: 'Aug',
    backgroundUrl: 'assets/images/belgium_bg.jpg',
    location: 'Belgium',
    venue: 'Circuit de \nSpa-Francorchamps',
    flagUrl: 'assets/images/belgium_flag.png',
    trackUrl: 'assets/images/belgium_track.png',
    circuitLength: '7.004',
    noLaps: '44',
    firstGp: '1950',
    raceDistance: '308.052',
    lapRecordTime: '1:46.286',
    lapRecordHolderYear: 'Valtteri Bottas (2018)',
  ),
  Race(
    round: 'Round 13',
    date: '03-05',
    month: 'Sep',
    backgroundUrl: 'assets/images/netherlands_bg.jpg',
    location: 'Netherlands',
    venue: 'Circuit Zandvoort',
    flagUrl: 'assets/images/netherlands_flag.png',
    trackUrl: 'assets/images/netherlands_track.png',
    circuitLength: '4.259',
    noLaps: '72',
    firstGp: '1952',
    raceDistance: '306.648',
    lapRecordTime: 'null',
    lapRecordHolderYear: 'null (null)',
  ),
  Race(
    round: 'Round 14',
    date: '10-12',
    month: 'Sep',
    backgroundUrl: 'assets/images/italy2_bg.jpg',
    location: 'Italy',
    venue: 'Autodromo Nazionale \nMonza',
    flagUrl: 'assets/images/italy2_flag.png',
    trackUrl: 'assets/images/italy2_track.png',
    circuitLength: '5.793',
    noLaps: '53',
    firstGp: '1950',
    raceDistance: '306.72',
    lapRecordTime: '1:21.046',
    lapRecordHolderYear: 'Rubens Barrichello (2004)',
  ),
  Race(
    round: 'Round 15',
    date: '24-26',
    month: 'Sep',
    backgroundUrl: 'assets/images/russia_bg.jpg',
    location: 'Russia',
    venue: 'Sochi Autodrom',
    flagUrl: 'assets/images/russia_flag.png',
    trackUrl: 'assets/images/russia_track.png',
    circuitLength: '5.848',
    noLaps: '53',
    firstGp: '2014',
    raceDistance: '309.745',
    lapRecordTime: '1:35.761',
    lapRecordHolderYear: 'Lewis Hamilton (2019)',
  ),
  Race(
    round: 'Round 16',
    date: '01-03',
    month: 'Oct',
    backgroundUrl: 'assets/images/turkey_bg.jpg',
    location: 'Turkey',
    venue: 'Intercity Istanbul \nPark',
    flagUrl: 'assets/images/turkey_flag.png',
    trackUrl: 'assets/images/turkey_track.png',
    circuitLength: '5.338',
    noLaps: '58',
    firstGp: '2005',
    raceDistance: '309.396',
    lapRecordTime: '1:24.770',
    lapRecordHolderYear: 'Juan Pablo Montoya (2005)',
  ),
  Race(
    round: 'Round 17',
    date: '08-10',
    month: 'Oct',
    backgroundUrl: 'assets/images/japan_bg.jpg',
    location: 'Japan',
    venue: 'Suzuka International \nRacing Course',
    flagUrl: 'assets/images/japan_flag.png',
    trackUrl: 'assets/images/japan_track.png',
    circuitLength: '5.807',
    noLaps: '58',
    firstGp: '2005',
    raceDistance: '307.471',
    lapRecordTime: '1:30.983',
    lapRecordHolderYear: 'Lewis Hamilton (2019)',
  ),
  Race(
    round: 'Round 18',
    date: '22-24',
    month: 'Oct',
    backgroundUrl: 'assets/images/us_bg.jpg',
    location: 'United States',
    venue: 'Circuit of The \nAmericas',
    flagUrl: 'assets/images/us_flag.png',
    trackUrl: 'assets/images/us_track.png',
    circuitLength: '5.513',
    noLaps: '56',
    firstGp: '2012',
    raceDistance: '308.405',
    lapRecordTime: '1:36.169',
    lapRecordHolderYear: 'Charles Leclerc (2019)',
  ),
  Race(
    round: 'Round 19',
    date: '29-31',
    month: 'Oct',
    backgroundUrl: 'assets/images/mexico_bg.jpg',
    location: 'Mexico',
    venue: 'Autódromo Hermanos \nRodríguez',
    flagUrl: 'assets/images/mexico_flag.png',
    trackUrl: 'assets/images/mexico_track.png',
    circuitLength: '4.304',
    noLaps: '71',
    firstGp: '1963',
    raceDistance: '305.354',
    lapRecordTime: '1:18.741',
    lapRecordHolderYear: 'Valtteri Bottas (2018)',
  ),
  Race(
    round: 'Round 20',
    date: '05-07',
    month: 'Nov',
    backgroundUrl: 'assets/images/brazil_bg.jpg',
    location: 'Brazil',
    venue: 'Autódromo José \nCarlos Pace',
    flagUrl: 'assets/images/brazil_flag.png',
    trackUrl: 'assets/images/brazil_track.png',
    circuitLength: '4.309',
    noLaps: '71',
    firstGp: '1973',
    raceDistance: '305.909',
    lapRecordTime: '1:10.540',
    lapRecordHolderYear: 'Valtteri Bottas (2018)',
  ),
  Race(
    round: 'Round 22',
    date: '03-05',
    month: 'Dec',
    backgroundUrl: 'assets/images/saudiArabia_bg.jpg',
    location: 'Saudi Arabia',
    venue: 'Jeddah Street Circuit',
    flagUrl: 'assets/images/saudiArabia_flag.png',
    trackUrl: 'assets/images/saudiArabia_track.png',
    circuitLength: '6.175',
    noLaps: '50',
    firstGp: '2021',
    raceDistance: '308.75',
    lapRecordTime: 'null',
    lapRecordHolderYear: 'null (null)',
  ),
  Race(
    round: 'Round 23',
    date: '10-12',
    month: 'Dec',
    backgroundUrl: 'assets/images/abuDhabi_bg.jpg',
    location: 'Abu Dhabi',
    venue: 'Yas Marina Circuit',
    flagUrl: 'assets/images/abuDhabi_flag.png',
    trackUrl: 'assets/images/abuDhabi_track.png',
    circuitLength: '5.554',
    noLaps: '55',
    firstGp: '2009',
    raceDistance: '305.355',
    lapRecordTime: '1:39.283',
    lapRecordHolderYear: 'Lewis Hamilton (2019)',
  ),
];